### ISSUE TITLE
Parallelize fetching remote tags

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/swift-outdated#6]
Since these don't depend on another, it should be possible to fetch tags for remotes simultaneously to decrease loading time.

**Comment by o15a3d4l11s2** [comment]
Do you have in mind how you want to do this?
If you are not in a hurry thing might be a great opportunity to try `async/awais` once it becomes part of Swift: https://github.com/apple/swift-evolution/blob/main/proposals/0296-async-await.md
Otherwise there are plenty of libraries providing promises, which would accomplish this. I am just curious 😀

**Comment by kiliankoe** [comment]
I thought about just using classic `DispatchGroup`s for now, but later refactoring to use async/await would be extremely cool!
